// Generated by CoffeeScript 1.9.2

/**
 */
var TAG, args, createNend, isTablet, makeAdmob, makeAdmobView;

args = arguments[0] || {};

$.adview.applyProperties(args);

TAG = "jp.coe.ad";

makeAdmobView = function(obj) {
  var Admob, ad;
  Admob = require("ti.admob");
  if (obj.adUnitId == null) {
    obj.adUnitId = Alloy.CFG.publisherId;
  }
  Ti.API.debug("obj.publisherId " + obj.adUnitId);
  console.debug((TAG + " ") + JSON.stringify(obj));
  ad = Admob.createView(obj);
  ad.addEventListener('didReceiveAd', function() {
    console.debug('Did receive ad!');
  });
  ad.addEventListener('didFailToReceiveAd', function() {
    console.debug('Failed to receive ad!');
  });
  ad.addEventListener('willPresentScreen', function() {
    console.debug('Presenting screen!');
  });
  ad.addEventListener('willDismissScreen', function() {
    console.debug('Dismissing screen!');
  });
  ad.addEventListener('didDismissScreen', function() {
    console.debug('Dismissed screen!');
  });
  ad.addEventListener('willLeaveApplication', function() {
    console.debug('Leaving the app!');
  });
  return ad;
};

makeAdmob = function(obj, tmpadview) {
  var admobview;
  Ti.API.debug("makeAdmob");
  if (tmpadview != null) {
    $.adview.remove(tmpadview);
  }
  admobview = makeAdmobView(obj);
  return $.adview.add(admobview);
};

createNend = function(obj) {
  var ad, adView;
  ad = require("net.nend");
  if (obj.nendId != null) {
    obj.apiKey = obj.nendId;
  }
  adView = ad.createView(obj);
  adView.addEventListener("receive", function(e) {
    return Ti.API.info("nend receive");
  });
  adView.addEventListener("error", function(e) {
    if (!ENV_PRODUCTION) {
      Ti.API.debug("nendエラー " + e);
    }
    Ti.API.debug("nendエラー " + e);
    return makeAdmob(obj, adView);
  });
  adView.addEventListener("click", function(e) {
    return Ti.API.info("nend click");
  });
  return adView;
};


/**
@deplicate
 */

isTablet = function() {
  return Alloy.isTablet;
};

exports.isTablet = isTablet;

exports.setBottom = function() {
  return $.adview.bottom = 0;
};

exports.setTop = function() {
  return $.adview.top = 0;
};

exports.init = function(obj, phonead) {
  var adview, is_tablet, ref, tmpadview;
  if (phonead == null) {
    phonead = false;
  }
  is_tablet = Alloy.isTablet;
  if (obj == null) {
    obj = is_tablet ? _.extend(Alloy.CFG.tablet, Alloy.CFG.ad_tablet) : _.extend(Alloy.CFG.phone, Alloy.CFG.ad_phone);
  }
  $.adview.height = Alloy.isTablet ? 90 : 50;
  $.adview.width = Alloy.isTablet ? 720 : 320;
  if ((ref = Alloy.CFG.ad) != null ? ref.hide : void 0) {
    return obj;
  }
  adview = null;
  if (false) {
    $.adview.add(createNend(obj));
  } else {
    if (Ti.UI.iOS != null) {
      tmpadview = Ti.UI.iOS.createAdView({
        zIndex: 1000
      });
      tmpadview.addEventListener('error', function(e) {
        Ti.API.error("AdView error");
        return makeAdmob(obj, tmpadview);
      });
      $.adview.add(tmpadview);
    } else if (Ti.Android != null) {
      adview = makeAdmobView(obj);
      $.adview.add(adview);
    }
  }
  return obj;
};
