// Generated by CoffeeScript 1.3.1
/**
*/

var args, createNend, isTablet, makeAdmob, makeAdmobView;

args = arguments[0] || {};

$.adview.applyProperties(args);

makeAdmobView = function(obj) {
  var Admob, admobview,
    _this = this;
  Admob = require("ti.admob");
  if (obj.publisherId == null) {
    obj.publisherId = Alloy.CFG.publisherId;
  }
  Ti.API.debug("obj.publisherId " + obj.publisherId);
  obj.kindAd = Alloy.isTablet ? 1 : 0;
  admobview = Admob.createView(obj);
  admobview.addEventListener("didReceiveAd", function(e) {
    return Ti.API.debug("didReceiveAd");
  });
  return admobview;
};

makeAdmob = function(obj, tmpadview) {
  var admobview;
  Ti.API.debug("makeAdmob");
  $.adview.remove(tmpadview);
  admobview = makeAdmobView(obj);
  return $.adview.add(admobview);
};

createNend = function(obj) {
  var ad, adView;
  ad = require("net.nend");
  if (obj.nendId != null) {
    obj.apiKey = obj.nendId;
  }
  adView = ad.createView(obj);
  adView.addEventListener("receive", function(e) {
    return Ti.API.info("nend receive");
  });
  adView.addEventListener("error", function(e) {
    if (!ENV_PRODUCTION) {
      Ti.API.debug("nendエラー " + e);
    }
    Ti.API.debug("nendエラー " + e);
    return makeAdmob(obj, adView);
  });
  adView.addEventListener("click", function(e) {
    return Ti.API.info("nend click");
  });
  return adView;
};

/**
@deplicate
*/


isTablet = function() {
  return Alloy.isTablet;
};

exports.isTablet = isTablet;

exports.setBottom = function() {
  return $.adview.bottom = 0;
};

exports.setTop = function() {
  return $.adview.top = 0;
};

exports.init = function(obj, phonead) {
  var adview, is_tablet, tmpadview,
    _this = this;
  if (phonead == null) {
    phonead = false;
  }
  is_tablet = Alloy.isTablet;
  if (obj == null) {
    obj = is_tablet ? _.extend(Alloy.CFG.tablet, Alloy.CFG.ad_tablet) : _.extend(Alloy.CFG.phone, Alloy.CFG.ad_phone);
  }
  $.adview.height = Alloy.isTablet ? 90 : 50;
  $.adview.width = Alloy.isTablet ? 720 : 320;
  if (Alloy.CFG.ad.hide) {
    return obj;
  }
  adview = null;
  if (Titanium.Locale.getCurrentCountry() === "JP" && !(OS_ANDROID && is_tablet)) {
    $.adview.add(createNend(obj));
  } else {
    if (Ti.UI.iOS != null) {
      tmpadview = Ti.UI.iOS.createAdView({
        zIndex: 1000
      });
      tmpadview.addEventListener('error', function(e) {
        Ti.API.error("AdView error");
        return makeAdmob(obj, tmpadview);
      });
      tmpadview.addEventListener('action', function(e) {
        Ti.API.debug("action");
        return makeAdmob(obj, tmpadview);
      });
      $.adview.add(tmpadview);
    } else if (Ti.Android != null) {
      adview = makeAdmobView(obj);
      $.adview.add(adview);
    }
  }
  return obj;
};
