// Generated by CoffeeScript 1.8.0

/**
 */
var args, createNend, isTablet, makeAdmob, makeAdmobView;

args = arguments[0] || {};

$.adview.applyProperties(args);

makeAdmobView = function(obj) {
  var Admob, admobview;
  Admob = require("ti.admob");
  if (obj.publisherId == null) {
    obj.publisherId = Alloy.CFG.publisherId;
  }
  Ti.API.debug("obj.publisherId " + obj.publisherId);
  obj.kindAd = Alloy.isTablet ? 1 : 0;
  admobview = Admob.createView(obj);
  admobview.addEventListener("didReceiveAd", (function(_this) {
    return function(e) {
      return Ti.API.debug("didReceiveAd");
    };
  })(this));
  return admobview;
};

makeAdmob = function(obj, tmpadview) {
  var admobview;
  Ti.API.debug("makeAdmob");
  $.adview.remove(tmpadview);
  admobview = makeAdmobView(obj);
  return $.adview.add(admobview);
};

createNend = function(obj) {
  var ad, adView;
  ad = require("net.nend");
  if (obj.nendId != null) {
    obj.apiKey = obj.nendId;
  }
  adView = ad.createView(obj);
  adView.addEventListener("receive", function(e) {
    return Ti.API.info("nend receive");
  });
  adView.addEventListener("error", function(e) {
    if (!ENV_PRODUCTION) {
      Ti.API.debug("nendエラー " + e);
    }
    Ti.API.debug("nendエラー " + e);
    return makeAdmob(obj, adView);
  });
  adView.addEventListener("click", function(e) {
    return Ti.API.info("nend click");
  });
  return adView;
};


/**
@deplicate
 */

isTablet = function() {
  return Alloy.isTablet;
};

exports.isTablet = isTablet;

exports.setBottom = function() {
  return $.adview.bottom = 0;
};

exports.setTop = function() {
  return $.adview.top = 0;
};

exports.init = function(obj, phonead) {
  var adview, is_tablet, tmpadview, _ref;
  if (phonead == null) {
    phonead = false;
  }
  is_tablet = Alloy.isTablet;
  if (obj == null) {
    obj = is_tablet ? _.extend(Alloy.CFG.tablet, Alloy.CFG.ad_tablet) : _.extend(Alloy.CFG.phone, Alloy.CFG.ad_phone);
  }
  $.adview.height = Alloy.isTablet ? 90 : 50;
  $.adview.width = Alloy.isTablet ? 720 : 320;
  if ((_ref = Alloy.CFG.ad) != null ? _ref.hide : void 0) {
    return obj;
  }
  adview = null;
  if (false) {
    $.adview.add(createNend(obj));
  } else {
    if (Ti.UI.iOS != null) {
      tmpadview = Ti.UI.iOS.createAdView({
        zIndex: 1000
      });
      tmpadview.addEventListener('error', (function(_this) {
        return function(e) {
          Ti.API.error("AdView error");
          return makeAdmob(obj, tmpadview);
        };
      })(this));
      tmpadview.addEventListener('action', (function(_this) {
        return function(e) {
          Ti.API.debug("action");
          return makeAdmob(obj, tmpadview);
        };
      })(this));
      $.adview.add(tmpadview);
    } else if (Ti.Android != null) {
      adview = makeAdmobView(obj);
      $.adview.add(adview);
    }
  }
  return obj;
};
